security.config:
    providers:
        main:
            entity: { class: SecurityBundle:User, property: username }
    firewalls:
        backend:
            pattern: /admin/.*
            form-login: true
            logout: true
