Application\JobeetBundle\Entity\JobeetJob:
  type: entity
  table: jobeet_job
  repositoryClass: Application\JobeetBundle\Entity\Repository\JobRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    type:
      type: string
      length: 255
    company:
      type: string
      length: 255
    logo:
      type: string
      length: 255
    url:
      type: string
      length: 255
    location:
      type: string
      length: 255            
    position:
      type: string
      length: 255  
    description:
      type: text
    how_to_apply:
      type: text
    token:
      type: string
      length: 255
    email:
      type: string
      length: 255       
    is_public:
      type: smallint
    is_activated:
      type: smallint     
    expires_at:
      type: datetime 
    created_at:
      type: datetime
    updated_at:
      type: datetime     
  manyToOne:
    category:
      targetEntity: Application\JobeetBundle\Entity\JobeetCategory
      joinColumn:
        name: category_id
        referencedColumnName: id      
  lifecycleCallbacks:
    prePersist: 
        - initSysFields
