<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ApplicationJobeetBundleEntityJobeetCategoryProxy extends \Application\JobeetBundle\Entity\JobeetCategory implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setSlug($slug)
    {
        $this->_load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->_load();
        return parent::getSlug();
    }

    public function addAffCategories(\Application\JobeetBundle\Entity\JobeetAffiliate $affCategories)
    {
        $this->_load();
        return parent::addAffCategories($affCategories);
    }

    public function getAffCategories()
    {
        $this->_load();
        return parent::getAffCategories();
    }

    public function addCategoryAffiliates(\Application\JobeetBundle\Entity\JobeetAffiliate $categoryAffiliates)
    {
        $this->_load();
        return parent::addCategoryAffiliates($categoryAffiliates);
    }

    public function getCategoryAffiliates()
    {
        $this->_load();
        return parent::getCategoryAffiliates();
    }

    public function addJobs(\Application\JobeetBundle\Entity\JobeetJob $jobs)
    {
        $this->_load();
        return parent::addJobs($jobs);
    }

    public function getJobs()
    {
        $this->_load();
        return parent::getJobs();
    }

    public function getActiveJobs()
    {
        $this->_load();
        return parent::getActiveJobs();
    }

    public function setActiveJobs($jobs)
    {
        $this->_load();
        return parent::setActiveJobs($jobs);
    }

    public function getActiveJobsCount()
    {
        $this->_load();
        return parent::getActiveJobsCount();
    }

    public function setActiveJobsCount($count)
    {
        $this->_load();
        return parent::setActiveJobsCount($count);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'slug', 'jobs', 'categoryAffiliates');
    }
}